# Generated by Django 5.1.6 on 2025-04-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товара'),
        ),
    ]
