# Generated by Django 5.1.6 on 2025-04-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
    ]
